const {test}=require('node:test');const assert=require('node:assert/strict');const ts=require('typescript');const fs=require('node:fs');
const decode=(file)=>ts.transpileModule(fs.readFileSync(file,'utf8').replace(/^import .*;\n/gm,''),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
function harness(overrides={}){
 const tables={admin_users:{id:'admin',role:'finance_admin',is_active:true},jobs:{id:'job',client_id:'client',status:'confirmed',payment_status:'refund_pending'},job_assignments:[],guard_payouts:[],transactions:{id:'payment',amount:92,stripe_payment_intent:'pi_test',status:'partially_refunded',refund_amount:20},...overrides.tables};
 const writes=[],refunds=[];const query=table=>{const result={data:tables[table],error:null};const p=new Proxy({}, {get(_,key){if(key==='then')return (resolve,reject)=>Promise.resolve(result).then(resolve,reject);return (...args)=>{if(['update','insert'].includes(key))writes.push([table,key,args[0]]);return p;}}});return p;};
 const db={from:query,auth:{getUser:async()=>overrides.authFailure?{data:{user:null},error:'bad token'}:{data:{user:{id:'admin-user'}},error:null}},rpc:async(name,args)=>{writes.push([name,args]);return name==='claim_financial_operation'?{data:overrides.replay?{id:'op',replayed:true,result:{success:true,refundId:'re_existing'}}:{id:'op',replayed:false},error:null}:{error:overrides.recordFailure?'audit failed':null};}};
 let handler;const helper={exports:{}};new Function('module','exports',decode('supabase/functions/_shared/financialOperations.ts'))(helper,helper.exports);
 class Stripe{constructor(){this.paymentIntents={retrieve:async()=>({status:'succeeded',latest_charge:{id:'ch_test',paid:true,amount:9200,amount_refunded:2000}})};this.refunds={create:async(body,options)=>{refunds.push({body,options});return {id:'re_test',status:'succeeded'};}};}}
 const Deno={env:{get:()=> 'configured'}};
 const m={exports:{}};new Function('module','exports','serve','Stripe','createClient','Deno',...Object.keys(helper.exports),decode('supabase/functions/execute-job-refund/index.ts'))(m,m.exports,h=>handler=h,Stripe,()=>db,Deno,...Object.values(helper.exports));
 const token='x.'+Buffer.from(JSON.stringify({aal:overrides.aal||'aal2'})).toString('base64url')+'.x';
 return {refunds,writes,request:async()=>handler(new Request('https://example.test/refund',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({jobId:'job'})}))};
}
test('invalid session, non-finance role and missing MFA cannot reach Stripe',async()=>{for(const [options,status] of [[{authFailure:true},401],[{tables:{admin_users:{role:'support_admin',is_active:true}}},403],[{aal:'aal1'},403]]){const h=harness(options);assert.equal((await h.request()).status,status);assert.equal(h.refunds.length,0);}});
test('payout in progress prevents admin refund before any Stripe write',async()=>{const h=harness({tables:{guard_payouts:[{status:'processing'}]}});assert.equal((await h.request()).status,409);assert.equal(h.refunds.length,0);});
test('partial-then-full admin refund submits only £72 with a stable idempotency key',async()=>{const h=harness();assert.equal((await h.request()).status,200);assert.equal(h.refunds[0].body.amount,7200);assert.equal(h.refunds[0].options.idempotencyKey,'job-refund:job:approved-job:v2');const rpc=h.writes.find(w=>w[0]==='record_financial_refund');assert.equal(rpc[1].p_cumulative_refund,92);});
test('completed operation replay submits no second refund',async()=>{const h=harness({replay:true});const res=await h.request();assert.equal(res.status,200);assert.equal((await res.json()).refundId,'re_existing');assert.equal(h.refunds.length,0);});
test('Stripe success with local failure holds for reconciliation instead of allowing another refund',async()=>{const h=harness({recordFailure:true});const r=await h.request();assert.equal(r.status,500);assert.match((await r.json()).error,/Do not repeat/);assert.equal(h.refunds.length,1);assert(h.writes.some(w=>w[0]==='financial_operations'&&w[2]?.state==='reconciliation_required'));});
test('dispute payout reserves records before Stripe and cannot downgrade an early successful webhook',async()=>{
 const writes=[];let handler,stripeCalled=false;
 const job={id:'job',client_id:'client',status:'completed',payment_status:'funded',guard_payout_amount:80,platform_fee:0,currency:'gbp'};
 const tables={admin_users:{role:'finance_admin',is_active:true},disputes:{id:'dispute',job_id:'job',status:'open',jobs:job,guards:{id:'guard',stripe_account_id:'acct_test',stripe_connect_status:'verified'}},job_assignments:{id:'assignment',status:'completed',payment_status:'funded'},transactions:{status:'completed',stripe_payment_intent:'pi_test',refunded:false,refund_amount:0},guard_payouts:[],financial_operations:{id:'op'}};
 const db={auth:{getUser:async()=>({data:{user:{id:'user'}},error:null})},rpc:async()=>({data:{id:'op',replayed:false},error:null}),from(table){let payload;const q=new Proxy({}, {get(_,key){if(key==='then')return(resolve,reject)=>{if(payload){writes.push({table,...payload,afterStripe:stripeCalled});if(table==='guard_payouts'&&payload.method==='insert')return Promise.resolve({data:{id:'payout'},error:null}).then(resolve,reject);}return Promise.resolve({data:tables[table],error:null}).then(resolve,reject);};return(...args)=>{if(['update','insert'].includes(key))payload={method:key,body:args[0]};return q;};}});return q;}};
 const helper={exports:{}};new Function('module','exports',decode('supabase/functions/_shared/financialOperations.ts'))(helper,helper.exports);
 class Stripe{constructor(){this.paymentIntents={retrieve:async()=>({status:'succeeded',latest_charge:{id:'ch_test',paid:true,amount:9200,amount_refunded:0}})};this.transfers={create:async()=>{assert(writes.some(w=>w.table==='guard_payouts'&&w.method==='insert'));assert(writes.some(w=>w.table==='job_assignments'&&w.body.payment_status==='payout_processing'));stripeCalled=true;tables.job_assignments.payment_status='paid_out';return{id:'tr_test'};}};}}
 const m={exports:{}};new Function('module','exports','serve','Stripe','createClient','Deno',...Object.keys(helper.exports),decode('supabase/functions/resolve-dispute/index.ts'))(m,m.exports,h=>handler=h,Stripe,()=>db,{env:{get:()=> 'configured'}},...Object.values(helper.exports));
 const token='x.'+Buffer.from(JSON.stringify({aal:'aal2'})).toString('base64url')+'.x';
 const response=await handler(new Request('https://example.test/dispute',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({dispute_id:'dispute',resolution:'resolved_guard'})}));
 assert.equal(response.status,200,await response.text());assert(stripeCalled);assert(!writes.some(w=>w.afterStripe&&['jobs','job_assignments','guard_payouts'].includes(w.table)&&(w.body.payment_status||w.body.status)));assert.equal(tables.job_assignments.payment_status,'paid_out');
});
