const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {PGlite}=require('@electric-sql/pglite');
const USER='11111111-1111-4111-8111-111111111111', CLIENT='22222222-2222-4222-8222-222222222222', JOB='33333333-3333-4333-8333-333333333333', ASSIGN='44444444-4444-4444-8444-444444444444';
async function setup(){const db=new PGlite();await db.exec(`
create role anon;create role authenticated;create role service_role;create schema app;
create table app.clients(id uuid,user_id uuid);
create table app.jobs(id uuid primary key,client_id uuid,status text,payment_status text,is_deleted boolean,disputed boolean,disputed_at timestamptz,disputed_reason text,updated_at timestamptz);
create table app.job_assignments(id uuid primary key,job_id uuid,guard_id uuid,status text default 'completed',payment_status text default 'funded',updated_at timestamptz);
create table app.job_completion_requests(id uuid primary key,job_id uuid,guard_id uuid,status text,client_approved_at timestamptz,client_disputed_at timestamptz,dispute_reason text,admin_approved_at timestamptz,admin_approved_by uuid,updated_at timestamptz);
create table app.admin_users(id uuid primary key,user_id uuid,role text,is_active boolean);
create table app.disputes(id uuid primary key default gen_random_uuid(),job_id uuid,client_id uuid,guard_id uuid,assignment_id uuid,raised_by text,reason text,details text,status text,created_at timestamptz default now());
create table app.financial_operations(job_id uuid,state text);
create table app.payment_audit_logs(job_id uuid,assignment_id uuid,guard_id uuid,client_id uuid,from_status text,to_status text not null,changed_by uuid,changed_by_role text,event_type text,reference_type text,reference_id text,details jsonb,reason text);
create table app.subscription_payments(id uuid default gen_random_uuid(),stripe_invoice_id text);
insert into app.clients values('${CLIENT}','${USER}');
insert into app.jobs values('${JOB}','${CLIENT}','confirmed','funded',false,false,null,null,null);
insert into app.job_assignments(id,job_id,guard_id) values('${ASSIGN}','${JOB}','77777777-7777-4777-8777-777777777777');
`);await db.exec(fs.readFileSync('supabase/migrations/20261004182919_atomic_payment_disputes.sql','utf8'));return db;}
const raise=(db,user=USER,assignment=ASSIGN)=>db.query('select app.raise_client_payment_dispute($1,$2,$3,$4,null) result',[user,JOB,assignment,'Sandbox dispute']);
test('dispute, independent finance hold and audit commit together; replay adds nothing',async()=>{const db=await setup();try{const first=(await raise(db)).rows[0].result;const second=(await raise(db)).rows[0].result;assert.equal(second.disputeId,first.disputeId);assert.equal(second.replayed,true);assert.equal((await db.query('select count(*)::int n from app.disputes')).rows[0].n,1);const job=(await db.query('select * from app.jobs')).rows[0];assert.equal(job.disputed,true);assert.equal(job.payment_status,'funded');assert.equal(job.status,'confirmed');assert.equal((await db.query('select count(*)::int n from app.payment_audit_logs')).rows[0].n,1);}finally{await db.close();}});
test('audit failure rolls back dispute and hold',async()=>{const db=await setup();try{await db.exec("alter table app.payment_audit_logs add constraint force_failure check(to_status <> 'disputed')");await assert.rejects(raise(db),/force_failure/);assert.equal((await db.query('select count(*)::int n from app.disputes')).rows[0].n,0);assert.equal((await db.query('select disputed from app.jobs')).rows[0].disputed,false);}finally{await db.close();}});
test('cross-client and cross-job assignment, unfunded job and processing payout are rejected',async()=>{const db=await setup();try{await assert.rejects(raise(db,'55555555-5555-4555-8555-555555555555'),/Client profile/);await db.exec("update app.job_assignments set job_id='66666666-6666-4666-8666-666666666666'");await assert.rejects(raise(db),/Assignment/);await db.exec(`update app.job_assignments set job_id='${JOB}';update app.jobs set payment_status='pending'`);await assert.rejects(raise(db),/not eligible/);await db.exec(`update app.jobs set payment_status='funded';insert into app.financial_operations values('${JOB}','processing')`);await assert.rejects(raise(db),/processing/);assert.equal((await db.query('select count(*)::int n from app.disputes')).rows[0].n,0);}finally{await db.close();}});
test('browser roles cannot execute privileged dispute RPC; invoice duplication is rejected',async()=>{const db=await setup();try{for(const role of ['anon','authenticated'])assert.equal((await db.query(`select has_function_privilege('${role}','app.raise_client_payment_dispute(uuid,uuid,uuid,text,text)','execute') allowed`)).rows[0].allowed,false);await db.exec("insert into app.subscription_payments(stripe_invoice_id) values('in_test')");await assert.rejects(db.exec("insert into app.subscription_payments(stripe_invoice_id) values('in_test')"),/subscription_payments_invoice_unique/);}finally{await db.close();}});

const REQUEST='88888888-8888-4888-8888-888888888888';
async function completion(db){await db.exec(`update app.jobs set status='awaiting_client_approval';insert into app.job_completion_requests(id,job_id,guard_id,status) values('${REQUEST}','${JOB}','77777777-7777-4777-8777-777777777777','pending')`);}
const decide=(db,action,user=USER)=>db.query('select app.record_completion_payment_decision($1,$2,$3,$4) result',[user,REQUEST,action,'Sandbox decision']);
test('completion approval commits its request, payout eligibility and audit together; duplicate is rejected',async()=>{const db=await setup();try{await completion(db);await decide(db,'approve');assert.equal((await db.query('select status from app.job_completion_requests')).rows[0].status,'approved');assert.equal((await db.query('select status from app.jobs')).rows[0].status,'payout_approved');assert.equal((await db.query('select payment_status from app.job_assignments')).rows[0].payment_status,'payout_pending');await assert.rejects(decide(db,'approve'),/already been processed/);}finally{await db.close();}});
test('completion dispute holds payout while preserving the funded job and can be resolved by finance',async()=>{const db=await setup();try{await completion(db);await decide(db,'dispute');assert.equal((await db.query('select disputed,payment_status from app.jobs')).rows[0].disputed,true);assert.equal((await db.query('select payment_status from app.jobs')).rows[0].payment_status,'funded');assert.equal((await db.query('select payment_status from app.job_assignments')).rows[0].payment_status,'disputed');await assert.rejects(decide(db,'admin_approve'),/Finance administrator/);await db.exec(`insert into app.admin_users values(gen_random_uuid(),'${USER}','finance_admin',true)`);await decide(db,'admin_approve');assert.equal((await db.query('select disputed,status from app.jobs')).rows[0].disputed,false);}finally{await db.close();}});
test('completion audit failure rolls back approval; cross-owner and independent Stripe hold cannot be released',async()=>{const db=await setup();try{await completion(db);await assert.rejects(decide(db,'approve','55555555-5555-4555-8555-555555555555'),/do not own/);await db.exec("alter table app.payment_audit_logs add constraint force_failure check(to_status <> 'payout_pending')");await assert.rejects(decide(db,'approve'),/force_failure/);assert.equal((await db.query('select status from app.job_completion_requests')).rows[0].status,'pending');assert.equal((await db.query('select payment_status from app.job_assignments')).rows[0].payment_status,'funded');await db.exec('alter table app.payment_audit_logs drop constraint force_failure');await decide(db,'dispute');await db.exec(`insert into app.admin_users values(gen_random_uuid(),'${USER}','finance_admin',true);update app.jobs set disputed_reason='Stripe dispute du_test: needs_response'`);await assert.rejects(decide(db,'admin_approve'),/independent payment dispute/);}finally{await db.close();}});
