const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {PGlite}=require('@electric-sql/pglite');const ts=require('typescript');
const GUARD='11111111-1111-4111-8111-111111111111',USER='22222222-2222-4222-8222-222222222222';
const payout=(status='pending',id='po_test')=>({id,amount:8000,currency:'gbp',status,created:1791153000,arrival_date:1791239400,livemode:false,bank_last4:'2345',failure_code:status==='failed'?'no_account':null,failure_message:status==='failed'?'Bank account not found':null});
async function setup(){const db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema app;create schema auth;create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;create table app.guards(id uuid primary key,user_id uuid,stripe_account_id text);create table app.admin_users(user_id uuid,is_active boolean,role text);grant usage on schema app,auth to authenticated,service_role;grant select on app.guards,app.admin_users to authenticated;create table app.payment_audit_logs(guard_id uuid,from_status text,to_status text not null,event_type text,stripe_event_id text,reference_type text,reference_id uuid,details jsonb);insert into app.guards values('${GUARD}','${USER}','acct_test');`);await db.exec(fs.readFileSync('supabase/migrations/20261004224222_guard_bank_payout_tracking.sql','utf8'));return db;}
const record=(db,status='pending',event=null,id='po_test',account='acct_test')=>db.query('select app.record_guard_bank_payout($1,$2::jsonb,$3) result',[account,JSON.stringify(payout(status,id)),event]);
test('bank payout lifecycle, duplicate events and repeated sync retain one ledger row',async()=>{const db=await setup();try{await record(db,'pending','evt_pending');await record(db,'in_transit','evt_transit');await record(db,'paid','evt_paid');await record(db,'paid','evt_paid');await record(db,'paid');const rows=(await db.query('select status,amount_minor,bank_last4 from app.guard_bank_payouts')).rows;assert.deepEqual(rows,[{status:'paid',amount_minor:8000,bank_last4:'2345'}]);assert.equal((await db.query('select count(*)::int n from app.payment_audit_logs')).rows[0].n,3);assert.equal((await db.query('select count(*)::int n from app.bank_payout_events')).rows[0].n,3);}finally{await db.close();}});
test('failure after paid remains failed when delayed paid/pending events arrive',async()=>{const db=await setup();try{await record(db,'paid','evt_paid');await record(db,'failed','evt_failed');await record(db,'paid','evt_oldpaid');await record(db,'pending','evt_oldpending');const row=(await db.query('select status,failure_code,failure_message from app.guard_bank_payouts')).rows[0];assert.deepEqual(row,{status:'failed',failure_code:'no_account',failure_message:'Bank account not found'});}finally{await db.close();}});
test('audit failure rolls back event and ledger, allowing genuine retry',async()=>{const db=await setup();try{await db.exec("alter table app.payment_audit_logs add constraint reject_paid check(to_status<>'paid')");await assert.rejects(record(db,'paid','evt_retry'),/reject_paid/);assert.equal((await db.query('select count(*)::int n from app.guard_bank_payouts')).rows[0].n,0);assert.equal((await db.query('select count(*)::int n from app.bank_payout_events')).rows[0].n,0);await db.exec('alter table app.payment_audit_logs drop constraint reject_paid');await record(db,'paid','evt_retry');assert.equal((await db.query('select status from app.guard_bank_payouts')).rows[0].status,'paid');}finally{await db.close();}});
test('unknown accounts and invalid payouts cannot write a ledger',async()=>{const db=await setup();try{assert.equal((await record(db,'paid',null,'po_unknown','acct_other')).rows[0].result.ignored_unknown_account,true);await assert.rejects(db.query('select app.record_guard_bank_payout($1,$2::jsonb,null)',['acct_test',JSON.stringify({...payout(),amount:-1})]),/Invalid/);assert.equal((await db.query('select count(*)::int n from app.guard_bank_payouts')).rows[0].n,0);}finally{await db.close();}});
test('guards can read only their own payouts; browser roles cannot mutate or read signing keys',async()=>{const db=await setup();try{await record(db,'paid');const privileges=(await db.query("select has_function_privilege('authenticated','app.record_guard_bank_payout(text,jsonb,text)','execute') rpc,has_table_privilege('authenticated','app.bank_payout_webhook_keys','select') secrets,has_table_privilege('authenticated','app.guard_bank_payouts','update') writes")).rows[0];assert.deepEqual(privileges,{rpc:false,secrets:false,writes:false});await db.exec(`set role authenticated;set test.uid='${USER}'`);assert.equal((await db.query('select count(*)::int n from app.guard_bank_payouts')).rows[0].n,1);await db.exec("set test.uid='33333333-3333-4333-8333-333333333333'");assert.equal((await db.query('select count(*)::int n from app.guard_bank_payouts')).rows[0].n,0);}finally{await db.close();}});
const source=fs.readFileSync('supabase/functions/_shared/bank-payouts.ts','utf8');const moduleBox={exports:{}};new Function('exports',ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(moduleBox.exports);
test('handler uses current connected-account Stripe payout and propagates persistence failure',async()=>{const calls=[];const stripe={payouts:{retrieve:async(id,params,options)=>{calls.push({id,params,options});return {...payout('failed'),destination:{object:'bank_account',last4:'2345'}}}}};let data;await moduleBox.exports.recordBankPayout({rpc:async(name,args)=>{data=args;return {data:{status:'failed'},error:null}}},stripe,'acct_test','po_test','evt_test');assert.equal(data.p_payout.status,'failed');assert.equal(calls[0].options.stripeAccount,'acct_test');await assert.rejects(moduleBox.exports.recordBankPayout({rpc:async()=>({error:{message:'database unavailable'}})},stripe,'acct_test','po_test'),/database unavailable/);});

function webhook({badSignature=false,failSave=false}={}){
 let handler;let saves=0;
 const db={from:()=>({select:()=>({eq:async()=>({data:[{signing_secret:'test_secret',livemode:false}],error:null})})})};
 class FakeStripe{constructor(){this.webhooks={constructEventAsync:async()=>{if(badSignature)throw Error('Signature mismatch');return {livemode:false,type:'payout.paid',account:'acct_test',id:'evt_test',data:{object:{id:'po_test'}}};}};}}
 const code=ts.transpileModule(fs.readFileSync('supabase/functions/stripe-bank-payout-webhook/index.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;
 const fakeRequire=name=>name.includes('stripe@')?{default:FakeStripe}:name.includes('supabase-js')?{createClient:()=>db}:{bankPayoutEventTypes:['payout.paid'],recordBankPayout:async()=>{saves++;if(failSave)throw Error('Database unavailable');return {status:'paid'};}};
 new Function('require','exports','Deno',code)(fakeRequire,{}, {env:{get:name=>name==='STRIPE_SECRET_KEY'?'sk_test_fixture':'fixture'},serve:fn=>{handler=fn;}});
 return {handler,saves:()=>saves};
}
test('webhook rejects missing or invalid signatures before persistence',async()=>{
 const good=webhook();assert.equal((await good.handler(new Request('https://example.test',{method:'POST',body:'{}'}))).status,400);assert.equal(good.saves(),0);
 const bad=webhook({badSignature:true});assert.equal((await bad.handler(new Request('https://example.test',{method:'POST',headers:{'stripe-signature':'bad'},body:'{}'}))).status,400);assert.equal(bad.saves(),0);
});
test('verified webhook returns a retryable failure when persistence fails',async()=>{
 const fake=webhook({failSave:true});const response=await fake.handler(new Request('https://example.test',{method:'POST',headers:{'stripe-signature':'verified'},body:'{}'}));assert.equal(response.status,500);assert.equal(fake.saves(),1);
});

test('earnings panel renders bank status, masked account and Stripe currency amounts',()=>{
 const rows=[{...payout('paid'),id:'one',amount_minor:8000,stripe_created_at:'2026-10-04',arrival_date:'2026-10-05'}, {...payout('failed'),id:'two',currency:'jpy',amount_minor:800,stripe_created_at:'2026-10-04',arrival_date:null}, {...payout('paid'),id:'three',currency:'isk',amount_minor:500,stripe_created_at:'2026-10-04',arrival_date:null}];
 let state=0;const react={...require('react'),useState:initial=>[state++===0?rows:initial,()=>{}],useCallback:fn=>fn,useEffect:()=>{}};
 const code=ts.transpileModule(fs.readFileSync('app/guard/earnings/BankPayoutTracker.tsx','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;
 const box={exports:{}};new Function('require','exports',code)(name=>name==='react'?react:name==='@/lib/supabase'?{supabase:{}}:require(name),box.exports);
 const html=require('react-dom/server').renderToStaticMarkup(require('react').createElement(box.exports.default,{guardId:GUARD}));
 assert.match(html,/£80\.00/);assert.match(html,/¥800/);assert.match(html,/ISK\s*5/);assert.match(html,/Paid to bank/);assert.match(html,/Failed/);assert.match(html,/Ending 2345/);assert.match(html,/Bank account not found/);assert.match(html,/Test/);
});
