const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const ts=require('typescript');
const ID='11111111-1111-4111-8111-111111111111';
function load(path,db,fetcher){let handler;const source=fs.readFileSync(path,'utf8').replace(/^import .*;\n/gm,'');const code=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS}}).outputText;new Function('serve','createClient','Deno','fetch',code)(fn=>handler=fn,(url,key,config)=>{assert.equal(config.global,undefined,'authorization is checked before service database operations');return db},{env:{get:()=> 'configured'}},fetcher);return handler;}
function database({user=true,assignmentGuard='guard',jobDisputed=false,decisionError=false}={}){const writes=[];const tables={guards:{id:'guard',user_id:'user',full_name:'Test guard'},clients:{id:'client',user_id:'user'},admin_users:null,job_assignments:{id:'assignment',job_id:'job',guard_id:assignmentGuard,status:'in_progress',payment_status:'funded',check_in_time:'2026-10-04T18:00:00Z',check_out_time:'2026-10-04T22:00:00Z'},jobs:{id:'job',client_id:'client',job_title:'Test',status:'in_progress',payment_status:'funded',disputed:jobDisputed},job_completion_requests:null};
const db={auth:{getUser:async()=>({data:{user:user?{id:'user'}:null}})},rpc:async(name,args)=>{writes.push({rpc:name,args});return {data:{success:true},error:decisionError?{message:'audit transaction failed'}:null}},from(table){let method='select',body,filters=[];const q={select:()=>q,eq:(key,value)=>{filters.push([key,value]);return q},insert:value=>{method='insert';body=value;return q},update:value=>{method='update';body=value;return q},delete:()=>{method='delete';return q},single:()=>q,maybeSingle:()=>q,then(resolve,reject){let data=tables[table]??null;if(data&&filters.some(([k,v])=>data[k]!==v))data=null;if(method==='insert'){writes.push({table,body});data={id:ID};}if(method==='update'){writes.push({table,body,filters});if(data)Object.assign(data,body);}return Promise.resolve({data,error:null}).then(resolve,reject)}};return q}};return {db,tables,writes};}
const request=(body,method='POST')=>new Request('https://example.test/function',{method,headers:{Authorization:'Bearer test','Content-Type':'application/json',Origin:'https://quickguard.uk'},...(method==='POST'?{body:JSON.stringify(body)}:{})});
test('guard completion checks its assignment owner and cannot complete another guard or mismatched job',async()=>{for(const opts of [{user:false},{assignmentGuard:'other'}]){const h=database(opts);const handler=load('supabase/functions/request-job-completion/index.ts',h.db,async()=>new Response('{}'));assert((await handler(request({jobId:'job',assignmentId:'assignment'}))).status>=400);assert.equal(h.writes.length,0);}const h=database();const handler=load('supabase/functions/request-job-completion/index.ts',h.db,async()=>new Response('{}'));assert.equal((await handler(request({jobId:'other',assignmentId:'assignment'}))).status,403);assert.equal(h.writes.length,0);});
test('funded checked-in/out guard can request completion; missing checkout and disputes block it',async()=>{const h=database();const handler=load('supabase/functions/request-job-completion/index.ts',h.db,async()=>new Response('{}'));const response=await handler(request({jobId:'job',assignmentId:'assignment'}));assert.equal(response.status,200);assert.equal(response.headers.get('Access-Control-Allow-Origin'),'https://quickguard.uk');assert(h.writes.some(w=>w.table==='job_assignments'&&w.body.status==='completed'));assert(h.writes.some(w=>w.table==='jobs'&&w.body.status==='awaiting_client_approval'));for(const opts of [{jobDisputed:true},{}]){const blocked=database(opts);if(!opts.jobDisputed)blocked.tables.job_assignments.check_out_time=null;const fn=load('supabase/functions/request-job-completion/index.ts',blocked.db,async()=>new Response('{}'));assert((await fn(request({jobId:'job',assignmentId:'assignment'}))).status>=400);assert.equal(blocked.writes.length,0);}});
test('completion endpoint responds to preflight and rejects missing body before any write',async()=>{const h=database();const handler=load('supabase/functions/request-job-completion/index.ts',h.db,async()=>new Response('{}'));assert.equal((await handler(request(null,'OPTIONS'))).status,200);assert.equal((await handler(request({}))).status,400);assert.equal((await handler(request(null,'GET'))).status,405);assert.equal(h.writes.length,0);});
function approvalHarness(options={}){const h=database(options);h.tables.job_completion_requests={id:ID,job_id:'job',guard_id:'guard',client_id:'client',status:'pending'};h.tables.job_assignments.status='completed';h.tables.jobs.status='awaiting_client_approval';const calls=[];const handler=load('supabase/functions/approve-job-completion/index.ts',h.db,async(url,args)=>{calls.push({url,args});return new Response(JSON.stringify({error:'Payout setup required'}),{status:400})});return {...h,calls,handler};}
test('atomic client approval reaches payout with then-only Supabase builders and reports setup pending honestly',async()=>{const h=approvalHarness();const response=await h.handler(request({requestId:ID,action:'approve'}));assert.equal(response.status,200);const result=await response.json();assert.equal(result.payoutInitiated,false);assert(result.payoutWarning);assert.equal(h.calls.length,1);assert.equal(JSON.parse(h.calls[0].args.body).internalApprovalSource,'client_completion_approved');assert(h.writes.some(w=>w.rpc==='record_completion_payment_decision'));assert(h.writes.some(w=>w.table==='payment_audit_logs'&&w.body.to_status==='payout_pending'));});
test('rejected atomic approval never invokes Stripe payout; completion dispute does not invoke payout',async()=>{const failed=approvalHarness({decisionError:true});assert.equal((await failed.handler(request({requestId:ID,action:'approve'}))).status,409);assert.equal(failed.calls.length,0);const dispute=approvalHarness();assert.equal((await dispute.handler(request({requestId:ID,action:'dispute',disputeReason:'Sandbox reason'}))).status,200);assert.equal(dispute.calls.length,0);assert.equal(dispute.writes.find(w=>w.rpc).args.p_action,'dispute');});
