const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {PGlite}=require('@electric-sql/pglite');
test('owner job insert/delete maintains counters while direct edits and cross-owner changes remain blocked',async()=>{
 const db=new PGlite();try{await db.exec(`create role authenticated;create role anon;create schema app;create schema auth;grant usage on schema app,auth to authenticated;create function auth.role() returns text language sql as $$select 'authenticated'::text$$;create function public.is_active_admin() returns boolean language sql as $$select false$$;create table app.clients(id uuid primary key,user_id uuid,verified bool,verification_status text,verified_at timestamptz,is_active bool,profile_completed bool,total_jobs_posted int,active_jobs int,total_spent numeric,stripe_customer_id text,payment_method_id text,subscription_plan text,subscription_tier text,subscription_status text,billing_cycle_day int,updated_at timestamptz);create table app.jobs(id uuid primary key,client_id uuid references app.clients,status text);grant all on app.clients,app.jobs to authenticated;alter table app.clients enable row level security;create policy client_own on app.clients to authenticated using(user_id::text=current_setting('test.uid')) with check(user_id::text=current_setting('test.uid'));alter table app.jobs enable row level security;create policy job_own on app.jobs to authenticated using(client_id in(select id from app.clients)) with check(client_id in(select id from app.clients));insert into app.clients(id,user_id,total_jobs_posted,active_jobs) values('11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222',0,0);select set_config('test.uid','22222222-2222-4222-8222-222222222222',false);`);
 await db.exec(fs.readFileSync('supabase/migrations/20261003203000_trusted_job_counter.sql','utf8'));await db.exec('create trigger protect before update on app.clients for each row execute function app.protect_client_server_fields();set role authenticated');
 await db.exec(`insert into app.jobs values('33333333-3333-4333-8333-333333333333','11111111-1111-4111-8111-111111111111','draft')`);
 assert.deepEqual((await db.query('select total_jobs_posted,active_jobs from app.clients')).rows,[{total_jobs_posted:1,active_jobs:0}]);
 await db.exec("update app.jobs set status='open'");assert.equal((await db.query('select active_jobs from app.clients')).rows[0].active_jobs,1);
 await assert.rejects(db.exec('update app.clients set active_jobs=999'),/protected client fields/);
 await assert.rejects(db.exec('update app.clients set verified=true'),/protected client fields/);
 await db.exec('delete from app.jobs');assert.deepEqual((await db.query('select total_jobs_posted,active_jobs from app.clients')).rows,[{total_jobs_posted:1,active_jobs:0}]);
 await db.exec('reset role');assert.equal((await db.query("select has_column_privilege('qg_job_counter_writer','app.clients','verified','UPDATE') allowed")).rows[0].allowed,false);
 }finally{await db.close();}
});
