import type { MetadataRoute } from 'next';

const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://quickguard.uk';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/admin/',
          '/auth/',
          '/guard/dashboard',
          '/guard/profile',
          '/guard/earnings',
          '/guard/bank-settings',
          '/guard/notification-settings',
          '/guard/complete-profile-wizard',
          '/guard/verification-pending',
          '/guard/verification-failed',
          '/guard/forgot-password',
          '/guard/reset-password',
          '/guard/job-invites',
          '/guard/jobs',
          '/guard/messages',
          '/guard/onboarding',
          '/guard/saved-jobs',
          '/guard/job-history',
          '/guard/payment-centre',
          '/guard/mobile',
          '/guard/notifications',
          '/guard/login',
          '/client/dashboard',
          '/client/jobs',
          '/client/post-job',
          '/client/payment-history',
          '/client/payment/',
          '/client/profile',
          '/client/complaints',
          '/client/complete-profile-wizard',
          '/client/forgot-password',
          '/client/reset-password',
          '/client/payment-centre',
          '/client/login',
          '/client/messages',
          '/client/notifications',
          '/client/onboarding',
          '/client/sites',
          '/client/support',
          '/client/templates',
          '/client/activity-log',
          '/client/reports',
          '/client/team-access',
          '/client/trust-safety',
          '/client/mobile',
          '/client/advanced-matching',
          '/client/bulk-posting',
          '/client/reviews',
          '/subscription/',
          '/accessibility-feedback/',
          '/maintenance',
          '/upgrade',
          '/payment/',
          '/company/',
        ],
      },
    ],
    sitemap: `${BASE_URL}/sitemap.xml`,
  };
}